### ISSUE TITLE
USER STORY: Close User Account

### ISSUE THREAD

**Issue by redfoxofwealden** [redfoxofwealden/tremaine-inn-booking-system#4]
EPIC: 
- #1 

As a customer I can close my account, so that I protect my privacy because I no longer need the services.

## Acceptance Criteria:
- User can close the account
- All bookings are canceled when the account is closed

## Tasks:
- [ ] Create or amend models
- [ ] Write code to delete user from databse
- [ ] Create form to delete user account
- [ ] Test
